name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
               docker build . --tag ghcr.io/quantori-inakhimov/alpine-test:latest
               docker run ghcr.io/quantori-inakhimov/alpine-test:latest
               docker push ghcr.io/quantori-inakhimov/alpine-test:latest

# name: scan
# on:
#   push:
#     branches:
#       - main


# env:
#   IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
#   IMAGE_PATH: images/alpine.dockerfile


# jobs:
#   build:
#     name: image scan
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       # - name: set up docker buildx
#       #   uses: docker/setup-buildx-action@v3
#       # - name: Build the image
#       #   uses: docker/build-push-action@v5
#       #   with:
#       #     context: .
#       #     file: images/alpine.dockerfile
#       #     tags: image/alpine:test-tag

#       # - name: Scan image
#       #   uses: anchore/scan-action@v3
#       #   with:
#       #     image: "image/alpine:test-tag"

#       - name: Run Trivy vulnerability scanner
#         uses: aquasecurity/trivy-action@master
#         with:
#           image-ref: 'node:20-alpine3.17'
#           format: 'table'
#           exit-code: '1'
#           ignore-unfixed: true
#           vuln-type: 'os,library'
#           severity: 'CRITICAL,HIGH'
          
#   # scan:
#   #   needs: ["build"]
#   #   name: Scan docker image with Checkov
#   #   uses: ./.github/workflows/scan-image.yaml
#   #   with:
#   #     DOCKER_TAG: alpine:${{ github.sha }}
