name: scan
on:
  push:
    branches:
      - main
jobs:
  build:
    name: image scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Scan docker image with Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          file: images/alpine.dockerfile
          framework: dockerfile
