name: scan
on:
  push:
    branches:
      - main


env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  IMAGE_PATH: images/alpine.dockerfile


jobs:
  build:
    name: image scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build the image
        run: docker build -t ${{ env.IMAGE_NAME }} ${{ env.IMAGE_PATH }}
      - name: Scan docker image with Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          dockerfile_path:  ${{ env.IMAGE_PATH }}
          docker_image: ${{ env.IMAGE_NAME }}
