name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
               docker build -f ./images/alpine.dockerfile --tag ghcr.io/quantori-inakhimov/alpine-test:latest .
               
               docker push ghcr.io/quantori-inakhimov/alpine-test:latest

      # - name: Run Trivy vulnerability scanner
      #   uses: aquasecurity/trivy-action@master
      #   with:
      #     image-ref: 'ghcr.io/quantori-inakhimov/alpine-test:latest'
      #     #format: 'table'
      #     exit-code: '1'
      #     ignore-unfixed: true
      #     vuln-type: 'os,library'
      #     severity: 'UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL'
      #     format: 'json'
      #     output: 'trivy-results.json'

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ghcr.io/quantori-inakhimov/alpine-test:latest
          annotations: true
          
      # - name: Upload Trivy scan results to GitHub Security tab
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'trivy-results.sarif'


      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   name: publish results
      #   with:
      #     name: my-artifact
      #     path: trivy-results.json


