name: scan
on:
  push:
    branches:
      - main


env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  IMAGE_PATH: images/alpine.dockerfile


jobs:
  build:
    name: image scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: images/alpine.dockerfile
          tags: alpine:${{ github.sha }}
      - name: Scan docker image with Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          dockerfile_path: images/alpine.dockerfile
          docker_image: alpine:${{ github.sha }}
